services:
  db:
    image: postgres
    env_file:
      - ../postgres.env
    expose:
      - 5432

  web-migrate:
    command: "./wait-for-it.sh db:5432 -- bash qa/test-migrate.sh"
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../superuser.env
      - ../postgres.env
    depends_on:
      - db

  web:
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../superuser.env
      - ../postgres.env
    depends_on:
      - web-migrate

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:8080"